version: "3.8"

services:
  accounts_db:
    image: mysql:latest
    volumes:
      - ./apps/accounts/db/data:/var/lib/mysql:delegated
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 3
    env_file:
      - ./apps/accounts/db/.env

  accounts:
    build:
      context: ./apps/accounts
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/accounts:/app
      - ./node_modules:/app/node_modules
    depends_on:
      accounts_db:
        condition: service_healthy

  gateway:
    build:
      context: ./apps/gateway
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/gateway:/app
      - ./node_modules:/app/node_modules
