# https://kubernetes.io/docs/concepts/workloaccounts/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-pod
  labels:
    app: accounts-pod
spec:
  selector:
    matchLabels:
      app: accounts-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: accounts-pod
    spec:
      containers:
        - name: accounts-container
          image: squaremarketacr.azurecr.io/squaremarket-accounts
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          env:
            - name: SERVER_NAME
              value: "Accounts"
            - name: SERVER_PORT
              value: "80"
            - name: MQ_CONNECTION_STRING
              value: "amqp://guest:guest@message-queue:5672"
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: DATABASE_NAME
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: DATABASE_PASSWORD
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: DATABASE_HOST
          ports:
            - containerPort: 80
      restartPolicy: Always
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
spec:
  selector:
    app: accounts-pod
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
