# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-pod
  labels:
    app: gateway-pod
spec:
  selector:
    matchLabels:
      app: gateway-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-pod
    spec:
      containers:
        - name: gateway-container
          image: squaremarketacr.azurecr.io/squaremarket-gateway:v0.1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /services.json
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          env:
            - name: SERVER_NAME
              value: "Gateway"
            - name: SERVER_PORT
              value: "80"
            - name: ALLOWED_ORIGIN
              valueFrom:
                secretKeyRef:
                  name: gateway-secrets
                  key: ALLOWED_ORIGIN
            - name: ACCOUNTS_SERVICE_URL
              value: http://accounts-service:8080
            - name: ADVERTISEMENTS_SERVICE_URL
              value: http://advertisements-service:8080
          ports:
            - containerPort: 80
      restartPolicy: Always
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-pod
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
