apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - account-deployment.yml
  - gateway-deployment.yml
  - advertisement-deployment.yml
  - message-queue-deployment.yml
  - gateway-ingress.yml

images:
  - name: squaremarketacr.azurecr.io/squaremarket-accounts
    newName: k3d-personal:9800/squaremarket-accounts
    newTag: latest
  - name: squaremarketacr.azurecr.io/squaremarket-gateway
    newName: k3d-personal:9800/squaremarket-gateway
    newTag: latest
  - name: squaremarketacr.azurecr.io/squaremarket-advertisements
    newName: k3d-personal:9800/squaremarket-advertisements
    newTag: latest

secretGenerator:
  - name: advertisement-service-secrets
    literals:
      - DATABASE_NAME=advertisements
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
      - DATABASE_HOST=192.168.48.1:3402

  - name: account-service-secrets
    literals:
      - DATABASE_NAME=accounts
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
      - DATABASE_HOST=192.168.48.1:3401
