# https://kubernetes.io/docs/concepts/workloadvertisements/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-pod
  labels:
    app: messages-pod
spec:
  selector:
    matchLabels:
      app: messages-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: messages-pod
    spec:
      containers:
        - name: messages-container
          image: squaremarketacr.azurecr.io/squaremarket-messages:v0.4
          imagePullPolicy: Always
          # resources:
          #   requests:
          #     cpu: 250m
          #     memory: 1Gi
          #   limits:
          #     cpu: 500m
          #     memory: 1Gi
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          env:
            - name: SERVER_NAME
              value: "messages"
            - name: SERVER_PORT
              value: "80"
            - name: MQ_CONNECTION_STRING
              value: "amqp://guest:guest@message-queue:5672"
            - name: AUTH_ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: AUTH_ISSUER_URL
            - name: AUTH_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: AUTH_AUDIENCE
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: messaging-service-secrets
                  key: DATABASE_NAME
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: messaging-service-secrets
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: messaging-service-secrets
                  key: DATABASE_PASSWORD
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: messaging-service-secrets
                  key: DATABASE_HOST
            - name: STORAGE_DRIVER
              valueFrom:
                secretKeyRef:
                  name: messaging-service-secrets
                  key: STORAGE_DRIVER
            - name: STORAGE_AZURE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: messaging-service-secrets
                  key: STORAGE_AZURE_CONNECTION_STRING
          ports:
            - containerPort: 80
      restartPolicy: Always
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: messages-service
spec:
  selector:
    app: messages-pod
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
