name: Build to Azure

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string

      project_name:
        required: true
        type: string

      registry:
        required: true
        type: string

    secrets:
      creds:
        required: true
        type: string
jobs:
    steps:

    - name: Azure Login
      uses: azure/login
      with:
        creds: ${{ secrets.creds }}

    - name: Build image on ACR
      working-directory: ./apps/${{ input.app }}
      uses: azure/CLI
      with:
        azcliversion: 2.29.1
        inlineScript: |
          az configure --defaults acr=${{ inputs.registry }}
          az acr build ${{ inputs.registry }}.azurecr.io/${{ inputs.project_name }}-${{ inputs.app }}:latest
