name: CD Accounts Azure

on:
  workflow_dispatch:
  pull_request:
    # types:
    #   - "closed"
    branches: [main, development]
    # paths:
    #   - "apps/accounts/**/*"

env:
  APP: accounts

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az account show

      - name: Build image on ACR
        uses: azure/CLI@v1
        with:
          azcliversion: 2.29.1
          inlineScript: |
            cd ./apps/${{ env.APP }}
            az configure --defaults acr=${{ env.AZURE_CONTAINER_REGISTRY }}
            az acr build ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.AZURE_PROJECT_NAME }}-${{ env.APP }}:latest
