name: CD Gateway Azure

on:
  workflow_dispatch:

  # pull_request:
  #   types:
  #     - "closed"
  #   branches: [main]
  #   paths:
  #     - "apps/gateway/**/*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Push to Azure
        uses: ./.github/workflows/reusable/build-to-azure.yml
        with:
          app: gateway
