name: CD Gateway Azure

on:
  workflow_dispatch:
  pull_request:
    # types:
    #   - "closed"
    branches: [main, development]
    # paths:
    #   - "apps/gateway/**/*"

jobs:
  build-and-push:
    uses: ./.github/workflows/build-to-azure.yml@${{ env.GITHUB_REF#refs/heads/ }}
    with:
      app: gateway
      project_name: ${{ env.AZURE_PROJECT_NAME }}
      registry: ${{ env.AZURE_CONTAINER_REGISTRY }}
      creds: ${{ secrets.AZURE_CREDENTIALS }}
