name: CD Azure

on:
  workflow_run:
    workflows:
      - "Gateway"
      - "Accounts"
    types:
      - "completed"
    branches: [main]

jobs:
  deploy-kubernetes:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
#     - name: Azure Login
#       uses: azure/login
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}
# #
#     - name: Gets K8s context
#       id: login
#       uses: azure/aks-set-context
#       with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}
#           resource-group: ${{ env.RESOURCE_GROUP }}
#           cluster-name: ${{ env.CLUSTER_NAME }}
#
#     # - name: Configure deployment
#     #   id: bake
#     #   uses: azure/k8s-bake
#     #   with:
#     #     renderEngine: 'helm'
#     #     helmChart: ${{ env.CHART_PATH }}
#     #     overrideFiles: ${{ env.CHART_OVERRIDE_PATH }}
#     #     overrides: |
#     #       replicas:2
#     #     helm-version: 'latest'
#
#     - name: Deploys application
#       uses: Azure/k8s-deploy
#       with:
#         manifests: ${{ steps.bake.outputs.manifestsBundle }}
#         images: |
#           ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.PROJECT_NAME }}:latest
#         imagepullsecrets: |
#           ${{ env.PROJECT_NAME }}
