name: CI gateway

on:
  pull_request:
    branches: [main, development]
    paths:
      - "apps/gateway/**/*"
  push:
    branches: [main, development]
    paths:
      - "apps/gateway/**/*"

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - name: Install Node.js dependencies
        run: npm ci -w apps/gateway
      - name: Run linters
        run: npm run lint -w apps/gateway
