name: Test frontend

on:
  pull_request:
    branches: [main, development]
    paths:
      - "apps/frontend/**/*"
  push:
    branches: [main, development]
    paths:
      - "apps/frontend/**/*"

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm ci -w apps/frontend
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:frontend
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: apps/frontend/playwright-report/
          retention-days: 30
